### ISSUE TITLE
NameError: name 'utterances' is not defined

### ISSUE THREAD

**Issue by jarcoder** [OpenVoiceOS/ovos-bidirectional-translation-plugin#3]
Hi! I found a small error in the __init__.py file.

In the last line, you have:

`return utterances, context`

However, it seems that the variable utterances is not defined in the current function, which causes a NameError. I suggest either defining utterances before returning it or, if it’s not needed, changing the line to:

`return context`

Please review this suggestion and let me know if there’s an update. Thanks!

**Comment by JarbasAl** [comment]
fixed!
